service: nestjs-typescript-challenge

frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 120
  stage: dev
  region: us-east-1
  environment: 
    PORT: "3000"
    JWT_SECRET: ${env:JWT_SECRET}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USER: ${env:DB_USER}
    DB_PASS: ${env:DB_PASS}
    DB_DATABASE: ${env:DB_DATABASE}
  vpc:
    securityGroupIds:
      - sg-d9111ee5
    subnetIds:
      - subnet-eced428a
      - subnet-371cef06
      - subnet-da6d0cd4
      - subnet-1fb61e40
      - subnet-d07bd1f1
      - subnet-84443bc9
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/AWSLambda_FullAccess
    - arn:aws:iam::aws:policy/AWSLambdaExecute

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /{proxy+}

custom:
  optimize:
    external: ['swagger-ui-dist']